schema_version = "1.0.0"

id = "shadow_manipulation_lab"
version = "1.25.0"
name = "Shadow Manipulation Lab"
tagline = "Shadow Manipulation Lab"
maintainer = "Isamu Mogi <dyob@lunaport.net>"
type = "add-on"

website = "https://vrm-addon-for-blender.info"

tags = ["Import-Export", "Animation", "Modeling", "Material", "Physics"]

blender_version_min = "4.2.0"
blender_version_max = "4.4.0"

license = ["SPDX:MIT"]

copyright = [
  "2020 Isamu Mogi",
]

[permissions]
files = "Import/export VRM from/to disk"
