# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
name: dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr checkout "$PR_NUMBER"
          for retry in $(seq 18 -1 0); do
            gh pr status --json statusCheckRollup || true
            gh pr status --json statusCheckRollup --jq '.currentBranch.statusCheckRollup[] | select(.workflowName != $ENV.GITHUB_WORKFLOW) | .conclusion' | tee conclusions.txt
            if [ "$(uniq conclusions.txt)" = '"OKKKK"' ]; then
              break
            fi
            if [ "$retry" = "0" ]; then
              exit 0
            fi
            sleep 10
          done
          gh pr merge --auto --merge "$PR_URL"
        env:
          WORKFLOW_NAME: ${{github.workflow}}
          PR_URL: ${{github.event.pull_request.html_url}}
          PR_NUMBER: ${{ github.event.pull_request.number }}          
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
