name: dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr checkout "$PR_NUMBER"

          for retry in $(seq 60 -1 0); do
            if [ "$retry" = "0" ]; then
              echo Timeout
              exit 1
            fi

            sleep 60

            gh pr status --json statusCheckRollup --jq . | tee statusCheckRollup.json
            jq '.currentBranch.statusCheckRollup[] | select(.workflowName != $ENV.GITHUB_WORKFLOW)' statusCheckRollup.json | tee CheckRuns.json
            if [ "$(jq .status CheckRuns.json | uniq)" != '"COMPLETED"' ]; then
              continue
            elif [ "$(jq .conclusion CheckRuns.json | uniq)" != '"SUCCESS"' ]; then
              echo Skip
              exit 0
            fi
            break
          done

          set -x

          git fetch
          current_hash=$(git rev-parse HEAD)
          base_ref_name=$(gh pr status --json baseRefName --jq .currentBranch.baseRefName)
          origin_base_ref_name="origin/$base_ref_name"
          if ! git rev-parse "$origin_base_ref_name"; then
            exit 1
          fi
          if ! git merge --ff-only "$origin_base_ref_name"; then
            git reset --hard "$current_hash"
            gh pr comment --body "@dependabot rebase"
            exit 0
          fi

          git reset --hard "$current_hash"

          for retry in $(seq 10); do
            if gh pr merge --auto --merge "$PR_URL"; then
              exit 0
            fi
            sleep 180
          done

          echo Error
          exit 1
        env:
          WORKFLOW_NAME: ${{github.workflow}}
          PR_URL: ${{github.event.pull_request.html_url}}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
