name: release-please

permissions: {}

on:
  workflow_run:
    workflows: ["lint"]
    branches: [main]
    types:
      - completed

jobs:
  release-please:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_release_created: ${{ steps.release.outputs.release_created }}
      release_sha: ${{ steps.release.outputs.sha }}
      release_tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これをやるとrelease-please-actionが安定する気がする
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # 通常の運用ではskip-github-pull-requestはfalseのままにする。
          # しかし、このレポジトリの運用ではrelease-please-actionがrelease-prがマージされたかを検知できないため
          # release-prがマージされたタイミングで、バージョンだけ進んだ不要なrelease-prが新規作成されてしまう。
          # それを防ぐため、はじめに `skip-github-pull-request: true` で一度release-please-actionを実行する。
          # 結果release_createdがfalseの場合ときは再度release-please-actionを実行し、通常通りrelease-prを
          # 作成したり更新したりする。
          skip-github-pull-request: true
      - uses: googleapis/release-please-action@v4
        if: ${{ !steps.release.outputs.release_created }}
  upload-release-archive:
    runs-on: ubuntu-24.04
    needs: release-please
    if: ${{ needs.release-please.result == 'success' && needs.release-please.outputs.release_release_created }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.release_sha }}
      - name: Release
        run: ./tools/release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ needs.release-please.outputs.release_tag_name }}
