on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["lint"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: lint
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これをやるとrelease-please-actionが安定する気がする

      - uses: googleapis/release-please-action@v4
        id: release

      - name: Release
        run: ./tools/release.sh
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ steps.release.outputs.tag_name }}
          RELEASE_UPLOAD_URL: ${{ steps.release.outputs.upload_url }}
