on:
  workflow_run:
    workflows: ["lint"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: lint
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これをやるとrelease-please-actionが安定する気がする

      - uses: googleapis/release-please-action@v4
        id: release

  upload-release-archive:
    runs-on: ubuntu-24.04
    needs: release-please
    steps:
      - name: Check Vars
        run: |
          echo "${{ needs.release-please }}"
          echo "${{ needs.release-please }}" | jq .
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.steps.release.outputs.sha }}
      - name: Release
        run: ./tools/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ needs.release-please.steps.release.outputs.tag_name }}
          RELEASE_UPLOAD_URL: ${{ needs.release-please.steps.release.outputs.upload_url }}
