on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          draft: true
          draft-pull-request: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: release-please-action
          extra-files: |
            shadow_manipulation_lab/__init__.py
      - name: Tweak Release
        run: |
          echo ${{ steps.release.outputs.tag_name }}
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/saturday06/VRM-Addon-for-Blender/releases/tags/${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
