on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これをやるとrelease-please-actionが安定する気がする

      - uses: googleapis/release-please-action@v4
        id: release

      - name: Trigger Status Check
        if: ${{ steps.release.outputs.prs_created }}
        run: |
          pr_number=$(echo '${{ steps.release.outputs.pr }}' | jq .number)
          gh pr checkout "$pr_number"
          git commit --allow-empty -m "chore: trigger status checks"
          git push origin HEAD
          exit 0

      - name: Release
        run: ./tools/release.sh
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG_NAME: ${{ steps.release.outputs.tag_name }}
          RELEASE_UPLOAD_URL: ${{ steps.release.outputs.upload_url }}
